version: "3.5"

volumes:
  config: {}
  data: {}
  license: {}
  logs: {}
  temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  um-server:
    image: store/softwareag/universalmessaging-server:10.11
    container_name: um-server
    hostname: um-server
    volumes:
      - temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - config:/opt/softwareag/common/conf/
      - data:/opt/softwareag/UniversalMessaging/server/umserver/data/
      - license:/opt/softwareag/UniversalMessaging/server/umserver/licence
      - logs:/opt/softwareag/UniversalMessaging/server/umserver/logs/
